name: Beta Release on tag push

on:
  push:
    tags:
      - "v*-beta"

permissions:
  contents: write
  packages: write

jobs:
  create-beta-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Create beta release
        uses: softprops/action-gh-release@v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "Beta release ${{ github.ref_name }}"
          body: |
            üß™ Beta Release voor test doeleinden

            **Tag:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}

            ‚ö†Ô∏è Dit is een pre-release versie.
          prerelease: true
          draft: false
          fail_on_unmatched_files: false
          generate_release_notes: false

  # -------------------------------------------------------------------------------- #

  build-beta-windows:
    needs: create-beta-release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Create .env file for build
        run: |
          @"
          DJANGO_RUNSERVER_HIDE_WARNING=true
          DEBUG=False
          LOG_LEVEL=INFO
          SECRET_KEY=${{ github.sha }}
          CSRF_TRUSTED_ORIGINS=http://127.0.0.1
          JOB_LOG_ONLY=True
          "@ | Out-File -FilePath "app\.env" -Encoding utf8
        shell: pwsh

      - name: Build core windows executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: "3.13.9"
          spec: "build.spec"
          requirements: "app/requirements.txt"

      - name: Trigger frontend repository webhook
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/Carmenda-nl/carmenda_pseudonymize_frontend/dispatches -d '{\"event_type\":\"backend-updated\"}'

      - name: Create zip archive
        run: |
          Compress-Archive -Path dist\backend\* -DestinationPath "Privacytool_backend_windows_${{ needs.create-beta-release.outputs.tag }}.zip"
        shell: pwsh

      - name: Upload to Beta pre-release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: ${{ needs.create-beta-release.outputs.tag }}
          files: "*.zip"
